### ISSUE TITLE
More info about Nextclouds and Groupfolder in 2023

### ISSUE THREAD

**Issue by delacosta456** [szaimen/Nextcloud-NAS-Guide#105]
hi
i read your interested documentation about Nextcloud-Nas (N-Nas) and thanking for taking time to write all those explanations.

I would like to know if :
- N-Nas solution can be used for an office that have 50 users.
- if improvement have now been done on Groupfolder App  which could let it work perfectly (with minor issue)
Thanks

**Comment by szaimen** [comment]
> * N-Nas solution can be used for an office that have 50 users.

Yes, should be possible. It mostly depends on available hardware. 

> * if improvement have now been done on Groupfolder App  which could let it work perfectly (with minor issue)

I am personally not using this app so better to ask this at https://help.nextcloud.com

**Comment by delacosta456** [comment]
hi
ok thanks for replying.
Did have any recommendation about alternative way to achieve what does Groupfolder App ?

**Comment by szaimen** [comment]
I am not saying that the app is not working now. I am simply not using the app because I dont need its features. Best is to ask your question in the forum.
