### ISSUE TITLE
Need more understanting with External Drive

### ISSUE THREAD

**Issue by delacosta456** [szaimen/Nextcloud-NAS-Guide#109]
hi
Please i need to understand in your guide how the user Data (datadirectory) is mapped to the external drive prepared with BTFRS.

I see no information about that in the guide unless i missed it

Thanks

**Comment by szaimen** [comment]
Hi, the datadir is positioned on the internal drive: https://szaimen.github.io/Nextcloud-NAS-Guide/nextcloud-installation/#5

However the data will then be mapped using local external storage from the external btrfs drive into Nextcloud: https://szaimen.github.io/Nextcloud-NAS-Guide/docs/create-shares

**Comment by delacosta456** [comment]
hi ok yhaks i see
But if i understand correctly this kind of manually structuring user's data is not really suitable for people or organazation with 100-1000+ user? because it will be very tedious create folders for each user..

Right ?

**Comment by szaimen** [comment]
> 100-1000+ user? because it will be very tedious create folders for each user..
> 
> Right ?

True
