### ISSUE TITLE
No previewgenerator in Additional Apps install

### ISSUE THREAD

**Issue by peterHeuz** [szaimen/Nextcloud-NAS-Guide#125]
Hello,

thank you very much for your thorough and verbose installation instructions!

In one of the last chapters [Customizing Nextcloud/Previewgenerator](https://szaimen.github.io/Nextcloud-NAS-Guide/docs/previewgenerator): On my machine - after having followed all steps, that worked like a charm - there is no app `Previewgenerator`.

Maybe it is already included in nextcloud by now? 

I decided to skip this step.

**Comment by szaimen** [comment]
Hey, thanks for the feedback! I think it was moved to the `old` folder by the upstream project: https://github.com/nextcloud/vm/tree/master/old. So we need to remove it from this documentation. Would you be up for creating the PR to do this? :)

**Comment by szaimen** [comment]
Done with https://github.com/szaimen/Nextcloud-NAS-Guide/commit/abc9820a7a3e9fa82dd3d5c2ebf796630adf9c30
