### ISSUE TITLE
User Deletion fails during initial Nextcloud Setup.

### ISSUE THREAD

**Issue by Moriarte** [szaimen/Nextcloud-NAS-Guide#55]
After webadmin user/pass is created, installer spits an error saying "ncadmin user cannot be deleted" and the script reruns on every subsequent boot. This occurs on multiple fresh installs of Ubuntu Server.

**Comment by szaimen** [comment]
Hello, thanks for your bugreport. Unfortunately this is a bug in Nextcloud 22.2.4. See https://github.com/nextcloud/server/issues/31092
You can work around this by removing `--not-latest` from the initial command that installs Nextcloud. This will then install 23.0.1 which should not have this problem. Thanks for your understanding.

**Comment by Moriarte** [comment]
Thanks!
